const questions=[
{type:"mc",prompt:"Kanji 「日」 berarti...",choices:["Hari / matahari","Bulan","Air","Api"],answer:0,explanation:"「日」 dapat berarti hari atau matahari."},
{type:"input",prompt:"Tulis Kanji untuk 'bulan'.",answer:"月",explanation:"Kanji untuk bulan adalah 「月」."},
{type:"tf",prompt:"「水」 berarti air.",answer:true,explanation:"Benar. 「水」 berarti air."}
];
let index=0,score=0,correct=0,wrong=0,student="",locked=false;
const gate=document.getElementById("nameGate"), quiz=document.getElementById("quiz"), counter=document.getElementById("counter"), timerEl=document.getElementById("timer");
document.getElementById("startBtn").onclick=()=>{student=document.getElementById("studentName").value.trim();if(!student){document.getElementById("nameError").textContent="Nama wajib diisi.";return}sessionStorage.setItem("bn_student",student);gate.classList.add("hidden");quiz.classList.remove("hidden");showQuestion()};
function showQuestion(){locked=false;const q=questions[index];counter.textContent=`${String(index+1).padStart(2,"0")}/${String(questions.length).padStart(2,"0")}`;let body=`<p class="eyebrow">SOAL ${index+1}</p><h2>${q.prompt}</h2>`;if(q.type==="mc")body+=`<div class="options">${q.choices.map((c,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}. ${c}</button>`).join("")}</div>`;if(q.type==="input")body+=`<input id="answerInput" placeholder="Ketik jawaban..."><div class="actions"><button id="submit" class="btn primary">JAWAB</button></div>`;if(q.type==="tf")body+=`<div class="options"><button class="option" data-v="true">BENAR</button><button class="option" data-v="false">SALAH</button></div>`;quiz.innerHTML=body;quiz.querySelectorAll(".option").forEach(b=>b.onclick=()=>check(q,q.type==="mc"?Number(b.dataset.i):b.dataset.v==="true",b));document.getElementById("submit")?.addEventListener("click",()=>check(q,document.getElementById("answerInput").value.trim(),null));startTimer(30)}
function check(q,value,button){if(locked)return;locked=true;let ok=q.type==="input"?value.toLowerCase()===q.answer.toLowerCase():value===q.answer;if(ok){correct++;score+=10}else wrong++;if(button)button.classList.add(ok?"correct":"wrong");quiz.insertAdjacentHTML("beforeend",`<div class="feedback"><b>${ok?"BENAR":"SALAH"}</b><br>${q.explanation}</div><button id="next" class="btn primary">${index===questions.length-1?"LIHAT HASIL":"LANJUT"}</button>`);document.getElementById("next").onclick=next}
function next(){index++;if(index>=questions.length){const result={name:student,score,correct,wrong,total:questions.length,accuracy:Math.round(correct/questions.length*100)};localStorage.setItem("bn_last_result",JSON.stringify(result));location.href="result.html"}else showQuestion()}
let interval;function startTimer(sec){clearInterval(interval);let left=sec;timerEl.textContent=`${left}s`;interval=setInterval(()=>{left--;timerEl.textContent=`${left}s`;if(left<=0){clearInterval(interval);if(!locked){locked=true;wrong++;quiz.insertAdjacentHTML("beforeend",`<div class="feedback"><b>WAKTU HABIS</b><br>${questions[index].explanation}</div><button id="next" class="btn primary">LANJUT</button>`);document.getElementById("next").onclick=next}}},1000)}
