let questions=[
{type:"mc",prompt:"Kanji 「日」 berarti...",choices:["Hari / matahari","Bulan","Air","Api"],answer:"0",points:10,explanation:"「日」 dapat berarti hari atau matahari."},
{type:"input",prompt:"Tulis Kanji untuk 'bulan'.",answer:"月",points:10,explanation:"Kanji untuk bulan adalah 「月」."},
{type:"tf",prompt:"「水」 berarti air.",answer:"true",points:10,explanation:"Benar. 「水」 berarti air."}
];
try{const saved=JSON.parse(localStorage.getItem('bn_questions')||'null');if(Array.isArray(saved)&&saved.length)questions=saved.filter(q=>q.active!==false).map(q=>({...q,answer:String(q.answer)}))}catch(e){}
let index=0,score=0,correct=0,wrong=0,student="",locked=false;const gate=document.getElementById("nameGate"),quiz=document.getElementById("quiz"),counter=document.getElementById("counter"),timerEl=document.getElementById("timer");
document.getElementById("startBtn").onclick=()=>{student=document.getElementById("studentName").value.trim();if(!student){document.getElementById("nameError").textContent="Nama wajib diisi.";return}sessionStorage.setItem("bn_student",student);gate.classList.add("hidden");quiz.classList.remove("hidden");showQuestion()};
function showQuestion(){locked=false;const q=questions[index];counter.textContent=`${String(index+1).padStart(2,"0")}/${String(questions.length).padStart(2,"0")}`;let body=`<p class="eyebrow">SOAL ${index+1}</p><h2>${q.prompt}</h2>`;if(q.type==="mc")body+=`<div class="options">${(q.choices||[]).map((c,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}. ${c}</button>`).join("")}</div>`;if(q.type==="input")body+=`<input id="answerInput" placeholder="Ketik jawaban..."><div class="actions"><button id="submit" class="btn primary">JAWAB</button></div>`;if(q.type==="tf")body+=`<div class="options"><button class="option" data-v="true">BENAR</button><button class="option" data-v="false">SALAH</button></div>`;quiz.innerHTML=body;quiz.querySelectorAll(".option").forEach(b=>b.onclick=()=>check(q,q.type==="mc"?String(b.dataset.i):b.dataset.v,b));document.getElementById("submit")?.addEventListener("click",()=>check(q,document.getElementById("answerInput").value.trim(),null));startTimer(30)}
function check(q,value,button){if(locked)return;locked=true;let ok=String(value).trim().toLowerCase()===String(q.answer).trim().toLowerCase();if(ok){correct++;score+=Number(q.points)||10}else wrong++;if(button)button.classList.add(ok?"correct":"wrong");quiz.insertAdjacentHTML("beforeend",`<div class="feedback"><b>${ok?"BENAR":"SALAH"}</b><br>${q.explanation||''}</div><button id="next" class="btn primary">${index===questions.length-1?"LIHAT HASIL":"LANJUT"}</button>`);document.getElementById("next").onclick=next}
function next(){index++;if(index>=questions.length){const result={name:student,score,correct,wrong,total:questions.length,accuracy:Math.round(correct/questions.length*100),at:new Date().toISOString()};localStorage.setItem("bn_last_result",JSON.stringify(result));const a=JSON.parse(localStorage.getItem('bn_results')||'[]');a.push(result);localStorage.setItem('bn_results',JSON.stringify(a));location.href="result.html"}else showQuestion()}
let interval;function startTimer(sec){clearInterval(interval);let left=sec;timerEl.textContent=`${left}s`;interval=setInterval(()=>{left--;timerEl.textContent=`${left}s`;if(left<=0){clearInterval(interval);if(!locked){locked=true;wrong++;quiz.insertAdjacentHTML("beforeend",`<div class="feedback"><b>WAKTU HABIS</b><br>${questions[index].explanation||''}</div><button id="next" class="btn primary">LANJUT</button>`);document.getElementById("next").onclick=next}}},1000)}
