-- AKEMI JAPAN — JFT-Basic 50 Soal (25 FOTO + 25 AUDIO)
-- Soal latihan original bergaya JFT-Basic, bukan soal resmi JFT.
alter table questions add column if not exists audio_text text;

do $$ declare pid uuid; begin
  select id into pid from parts where part_number=1 limit 1;
  if pid is null then
    insert into parts (part_number,name,description,question_limit,shuffle_questions,shuffle_options,active)
    values (1,'JFT-Basic — 50 Soal','Latihan JFT-Basic: 25 soal foto + 25 soal audio. Pilih jumlah soal dan timer sendiri.',50,true,true,true) returning id into pid;
  else
    update parts set name='JFT-Basic — 50 Soal', description='Latihan JFT-Basic: 25 soal foto + 25 soal audio. Pilih jumlah soal dan timer sendiri.', question_limit=50, shuffle_questions=true, shuffle_options=true, active=true where id=pid;
  end if;
  delete from questions where part_id=pid;
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'この ばしょは なんですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["えき", "びょういん", "ぎんこう", "ホテル"]','えき',null,null,'01_train.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにを しますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["ごはんを たべます", "ほんを よみます", "くすりを もらいます", "でんしゃを まちます"]','ごはんを たべます',null,null,'02_restaurant.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにが できますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["かいものが できます", "びょうきの そうだんを します", "でんしゃに のります", "しごとを します"]','かいものが できます',null,null,'03_supermarket.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'この ばしょは なんですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["びょういん", "ホテル", "えき", "ぎんこう"]','びょういん',null,null,'04_hospital.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにを しますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["おかねを ひきだします", "ほんを かります", "ごはんを たべます", "でんしゃを まちます"]','おかねを ひきだします',null,null,'05_bank.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'この みせで かえそうな ものは どれですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["おにぎり", "でんしゃ", "びょういん", "ホテル"]','おにぎり',null,null,'06_convenience.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'この てんきなら、なにを もって いきますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["かさ", "うちわ", "せんぷうき", "ぼうし"]','かさ',null,null,'07_umbrella.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'なんじごろですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["９じごろ", "３じごろ", "１２じごろ", "６じごろ"]','９じごろ',null,null,'08_clock.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'この ばしょで よく することは どれですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["しごとを します", "およぎます", "ねます", "りょうりします"]','しごとを します',null,null,'09_office.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにを しますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["べんきょうします", "かいものします", "くるまを なおします", "おかねを かります"]','べんきょうします',null,null,'10_classroom.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'これは なんですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["じてんしゃ", "でんしゃ", "くるま", "ひこうき"]','じてんしゃ',null,null,'11_bicycle.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'これは なんに つかいますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["でんしゃなどに のる", "ほんを よむ", "ごはんを つくる", "びょういんへ いく"]','でんしゃなどに のる',null,null,'12_ticket.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'この のみものは どれですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["コーヒー", "おちゃ", "みず", "ぎゅうにゅう"]','コーヒー',null,null,'13_coffee.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'この しゃしんから わかることは どれですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["かぞくが います", "ひとりです", "せんせいです", "おきゃくさんです"]','かぞくが います',null,null,'14_family.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'これで なにが できますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["でんわを かけます", "くつを はきます", "ごはんを たべます", "でんしゃに のります"]','でんわを かけます',null,null,'15_phone.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'これは なんですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["バス", "でんしゃ", "タクシー", "じてんしゃ"]','バス',null,null,'16_bus.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにを しますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["さんぽします", "びょういんへ いきます", "おかねを かります", "べんきょうします"]','さんぽします',null,null,'17_park.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにを しますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["てがみを おくります", "ごはんを たべます", "くすりを もらいます", "でんしゃに のります"]','てがみを おくります',null,null,'18_postoffice.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'この ばしょは なんですか。','','Pilih jawaban yang paling tepat.','multiple_choice','["がっこう", "ホテル", "ぎんこう", "えき"]','がっこう',null,null,'19_school.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにを しますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["とまります", "かいものします", "しごとを します", "びょういんへ いきます"]','とまります',null,null,'20_hotel.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'この みせで なにを しますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["たべものを かいます", "でんしゃに のります", "くすりを もらいます", "ねます"]','たべものを かいます',null,null,'21_supermarket2.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにを しますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["りょうりします", "べんきょうします", "おかねを かります", "でんわを かけます"]','りょうりします',null,null,'22_kitchen.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにを しますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["ほんを よみます", "ごはんを たべます", "およぎます", "くすりを もらいます"]','ほんを よみます',null,null,'23_library.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'ここで なにを まちますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["でんしゃ", "びょういん", "ほん", "ごはん"]','でんしゃ',null,null,'24_station2.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'あめの ひに なにを つかいますか。','','Pilih jawaban yang paling tepat.','multiple_choice','["かさ", "サングラス", "せんぷうき", "うちわ"]','かさ',null,null,'25_weather.svg',null,null,true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["えきの となりです", "５じです", "１００えんです", "げんきです"]','えきの となりです',null,null,null,null,'トイレは どこですか。 えきの となりです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["げつようび", "すいようび", "きんようび", "にちようび"]','すいようび',null,null,null,null,'あしたは なんようびですか。 すいようびです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["３００えん", "３００じ", "３００にん", "３００だい"]','３００えん',null,null,null,null,'コーヒーを おねがいします。 ３００えんです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["えきで まちます", "うみで およぎます", "ほんを かいます", "うちで りょうりします"]','えきで まちます',null,null,null,null,'でんしゃが おくれています。 えきで まちます。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["そうですね", "いただきます", "おやすみなさい", "どうぞ"]','そうですね',null,null,null,null,'きょうは さむいですね。 そうですね。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["ごご２じ", "ごぜん２じ", "ごご１２じ", "あさ７じ"]','ごご２じ',null,null,null,null,'なんじに あいますか。 ごご２じに あいましょう。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["わたしのです", "わたしもです", "どういたしまして", "しりませんでした"]','わたしのです',null,null,null,null,'この かさは だれのですか。 わたしのです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["いそがしいです", "ひまです", "やすみです", "びょうきです"]','いそがしいです',null,null,null,null,'きょう ひまですか。 いいえ、しごとが あります。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["いいえ、だめです", "はい、さようなら", "おめでとうございます", "いただきます"]','いいえ、だめです',null,null,null,null,'ここで たばこを すっても いいですか。 いいえ、だめです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["かいしゃの ちかくの みせ", "うち", "えきの なか", "びょういん"]','かいしゃの ちかくの みせ',null,null,null,null,'どこで ひるごはんを たべますか。 かいしゃの ちかくの みせです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["すみません、ちょっと ようじが あります", "はい、よろこんで", "いただきます", "おだいじに"]','すみません、ちょっと ようじが あります',null,null,null,null,'あした いっしょに えいがを みませんか。 すみません、ちょっと ようじが あります。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["バスで １０ぷんぐらい", "あるいて １じかん", "でんしゃで １ぷん", "タクシーで ２じかん"]','バスで １０ぷんぐらい',null,null,null,null,'えきまで どうやって いきますか。 バスで １０ぷんぐらいです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["らいげつ", "きょう", "きのう", "らいしゅう"]','らいげつ',null,null,null,null,'いつ くにへ かえりますか。 らいげつです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["６じ３０ぷんごろ", "５じ３０ぷんごろ", "７じごろ", "６じ１５ふんごろ"]','６じ３０ぷんごろ',null,null,null,null,'いま なんじですか。 ６じ はんです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["１５０えん", "１００えん", "２００えん", "５０えん"]','１５０えん',null,null,null,null,'この りんごは いくらですか。 ひとつ １５０えんです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["９じ", "７じ", "１２じ", "５じ"]','９じ',null,null,null,null,'しごとは なんじからですか。 ９じからです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["えいがを みます", "しごとを します", "うちで ねます", "べんきょうします"]','えいがを みます',null,null,null,null,'あした なにを しますか。 ともだちと えいがを みます。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["どうぞ", "さようなら", "おめでとう", "おやすみなさい"]','どうぞ',null,null,null,null,'すみません、みずを おねがいします。 はい、どうぞ。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["スーパー", "びょういん", "がっこう", "こうえん"]','スーパー',null,null,null,null,'きのう どこへ いきましたか。 スーパーへ いきました。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["０９０の１２３４", "５じです", "えきです", "げんきです"]','０９０の１２３４',null,null,null,null,'でんわばんごうは なんですか。 ０９０の１２３４です。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["はい、ひまです", "いいえ、ねます", "おだいじに", "いただきます"]','はい、ひまです',null,null,null,null,'らいしゅう どようびは ひまですか。 はい、ひまです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["ラーメン", "みず", "ほん", "くつ"]','ラーメン',null,null,null,null,'なにを たべたいですか。 ラーメンを たべたいです。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["はい、とまります", "いいえ、たべます", "５じです", "１００えんです"]','はい、とまります',null,null,null,null,'この でんしゃは えきに とまりますか。 はい、とまります。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["バスで きました", "９じです", "きょうです", "げんきです"]','バスで きました',null,null,null,null,'なんで きましたか。 バスで きました。',true);
  insert into questions (part_id,prompt,reading,instruction,type,options,answer,media_url,media_type,photo_url,audio_url,audio_text,active) values (pid,'Dengarkan audio berikut, lalu pilih jawaban yang tepat.','','Pilih jawaban yang paling tepat.','multiple_choice','["はい、かえります", "いただきます", "おめでとうございます", "おだいじに"]','はい、かえります',null,null,null,null,'もう かえりますか。 はい、かえります。',true);
end $$;
notify pgrst, 'reload schema';
