-- AKEMI JAPAN — JFT-Basic 50 soal original
-- Tambahkan/ulang seed JFT tanpa menyentuh Part lain.
alter table questions add column if not exists audio_text text;
DO $$
DECLARE
  pid uuid;
  pn int;
BEGIN
  -- Jika seed JFT pernah dipasang, hapus hanya Part JFT milik seed ini.
  DELETE FROM questions WHERE part_id IN (SELECT id FROM parts WHERE name = 'JFT-Basic — 50 Soal');
  DELETE FROM parts WHERE name = 'JFT-Basic — 50 Soal';

  SELECT n INTO pn
  FROM generate_series(1,20) AS n
  WHERE NOT EXISTS (SELECT 1 FROM parts p WHERE p.part_number=n)
  ORDER BY n
  LIMIT 1;

  IF pn IS NULL THEN
    RAISE EXCEPTION 'Tidak ada nomor Part kosong (1-20). Hapus/nonaktifkan satu Part terlebih dahulu.';
  END IF;

  INSERT INTO parts(part_number,name,description,question_limit,shuffle_questions,shuffle_options,active)
  VALUES(pn,'JFT-Basic — 50 Soal','Latihan JFT-Basic original: campuran teks, foto, dan audio. Semua soal pilihan ganda.',50,true,true,true)
  RETURNING id INTO pid;

  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'どこで くつを ぬぎますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["げんかん", "だいどころ", "おふろ", "えき"]','げんかん',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'あした なんじに きますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["7じ", "8じ", "9じ", "10じ"]','7じ',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'この でんしゃは とうきょうへ いきますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["はい、いきます", "いいえ、たべます", "はい、のみます", "いいえ、よみます"]','はい、いきます',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'「すみません」は いつ つかいますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["あやまる とき", "ねる とき", "たべる とき", "はしる とき"]','あやまる とき',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'きょうは なんようびですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["げつようび", "みず", "はちじ", "さんがつ"]','げつようび',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'まいあさ パンを たべます。これは なんですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["しゅうかん", "てんき", "ばしょ", "しごと"]','しゅうかん',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'この へやは ちょっと さむいです。まどを ____。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["しめて ください", "たべて ください", "よんで ください", "きいて ください"]','しめて ください',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'「いっしょに ひるごはんを たべませんか。」の いみは？',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["ajak makan siang bersama", "ajak pulang", "minta uang", "minta izin tidur"]','ajak makan siang bersama',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'きのう えいがを ____。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["みました", "みます", "みません", "みるです"]','みました',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'これは わたしの かさです。あれは ____です。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["ともだちの", "ともだちを", "ともだちに", "ともだちが"]','ともだちの',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'しごとは 9じから 5じ ____です。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["まで", "までに", "しか", "ごろ"]','まで',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'ここで しゃしんを ____も いいですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["とって", "とる", "とった", "とり"]','とって',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'この くすりは いつ のみますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["あさと ばん", "あしたの まえ", "えきで", "きのう"]','あさと ばん',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'らいしゅう きょうとへ ____。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["いきます", "いきました", "いって", "いかないです"]','いきます',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'わたしは りょうりが ____です。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["すき", "すきな", "すきに", "すきで"]','すき',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'きょうは あめです。かさを ____。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["もちます", "ねます", "よみます", "あそびます"]','もちます',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'「ここから えきまで どうやって いきますか。」と きかれました。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["バスで いきます", "えきで いきます", "えきを たべます", "バスが すきです"]','バスで いきます',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'この りんごは いくらですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["300えんです", "3じです", "3にんです", "300メートルです"]','300えんです',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'あした ひまです。いっしょに ____。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["えいがを みませんか", "えいがを みました", "えいがが ありません", "えいがを みるでした"]','えいがを みませんか',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'でんわで「もしもし」と いいました。つぎに なんと いいますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["はい、たなかです", "いただきます", "おやすみなさい", "いってきます"]','はい、たなかです',NULL,NULL,NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'この のりものは なんですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["バス", "でんしゃ", "ひこうき", "じてんしゃ"]','バス','image','jft-media/photo-01.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'これは なんですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["でんしゃ", "くるま", "バス", "タクシー"]','でんしゃ','image','jft-media/photo-02.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'この たべものは なんですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["りんご", "みかん", "パン", "たまご"]','りんご','image','jft-media/photo-03.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'あめの ひに つかう ものは どれですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["かさ", "くつ", "ぼうし", "かばん"]','かさ','image','jft-media/photo-04.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'この しゃしんの じかんは なんじごろですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["3じごろ", "9じごろ", "12じごろ", "6じごろ"]','3じごろ','image','jft-media/photo-05.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'ここは どこですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["レストラン", "びょういん", "ぎんこう", "としょかん"]','レストラン','image','jft-media/photo-06.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'びょうきの とき、どこへ いきますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["びょういん", "こうえん", "えき", "ゆうびんきょく"]','びょういん','image','jft-media/photo-07.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'たべものを かいたいです。どこへ いきますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["スーパー", "びょういん", "こうえん", "えき"]','スーパー','image','jft-media/photo-08.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'この ばしょは どこですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["こうえん", "レストラン", "ホテル", "がっこう"]','こうえん','image','jft-media/photo-09.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'てがみを おくりたいです。どこへ いきますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["ゆうびんきょく", "びょういん", "スーパー", "えき"]','ゆうびんきょく','image','jft-media/photo-10.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'これは なんですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["みず", "おちゃ", "ぎゅうにゅう", "コーヒー"]','みず','image','jft-media/photo-11.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'これは はく ものです。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["くつ", "かさ", "ぼうし", "シャツ"]','くつ','image','jft-media/photo-12.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'これは なんですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["でんわ", "テレビ", "カメラ", "ラジオ"]','でんわ','image','jft-media/photo-13.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'この ひとは だれですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["かぞく", "せんせい", "いしゃ", "ともだち"]','かぞく','image','jft-media/photo-14.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'ここに トイレが あります。どの ひょうしきですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["トイレ", "えき", "びょういん", "レストラン"]','トイレ','image','jft-media/photo-15.svg',NULL,NULL,true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、ただしい ものを えらんでください。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["あさ 7じです", "ひる 7じです", "よる 7じです", "あさ 9じです"]','あさ 7じです','audio',NULL,NULL,'あさ 7じです',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、どこへ いきますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["スーパー", "びょういん", "えき", "こうえん"]','スーパー','audio',NULL,NULL,'スーパーへ いきます。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、なにを たべますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["パン", "ごはん", "りんご", "うどん"]','パン','audio',NULL,NULL,'あさごはんに パンを たべます。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、なんじに でますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["8じ", "9じ", "10じ", "11じ"]','8じ','audio',NULL,NULL,'8じに いえを でます。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、だれと いきますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["ともだち", "せんせい", "かぞく", "ひとり"]','ともだち','audio',NULL,NULL,'ともだちと いきます。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、なにを かいますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["みず", "くつ", "かさ", "ほん"]','みず','audio',NULL,NULL,'スーパーで みずを かいます。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、あしたの てんきは どうですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["あめ", "はれ", "ゆき", "くもり"]','あめ','audio',NULL,NULL,'あしたは あめです。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、どこで ひるごはんを たべますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["レストラン", "いえ", "がっこう", "こうえん"]','レストラン','audio',NULL,NULL,'レストランで ひるごはんを たべます。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、なんようびですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["げつようび", "かようび", "すいようび", "もくようび"]','かようび','audio',NULL,NULL,'きょうは かようびです。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、なにを しますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["べんきょうします", "ねます", "はたらきます", "そうじします"]','べんきょうします','audio',NULL,NULL,'よる、にほんごを べんきょうします。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、いくらですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["500えん", "600えん", "700えん", "800えん"]','700えん','audio',NULL,NULL,'これは 700えんです。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、どうやって いきますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["バスで", "でんしゃで", "じてんしゃで", "あるいて"]','でんしゃで','audio',NULL,NULL,'えきまで でんしゃで いきます。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、いつ かえりますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["5じ", "6じ", "7じ", "8じ"]','6じ','audio',NULL,NULL,'6じに うちへ かえります。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、なにが ほしいですか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["コーヒー", "おちゃ", "みず", "ジュース"]','おちゃ','audio',NULL,NULL,'おちゃが ほしいです。',true);
  INSERT INTO questions(part_id,prompt,reading,instruction,type,options,answer,media_type,photo_url,audio_url,audio_text,active) VALUES (pid,'おとを きいて、だれに でんわしますか。',NULL,'Pilih jawaban yang paling tepat.','multiple_choice','["たなかさん", "やまださん", "せんせい", "おかあさん"]','たなかさん','audio',NULL,NULL,'たなかさんに でんわします。',true);
END $$;
