-- ITCO JAPAN | PART 01 | SOAL 41-50
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、かいしゃで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しりょうを まとめます','よていを かくにんします','メールを おくります','かいぎを します'),'メールを おくります','q016.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、びょういんで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('くすりを もらいます','よやくを かくにんします','うけつけを します','せんせいに そうだんします'),'よやくを かくにんします','q017.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、ぎんこうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しつもんします','おかねを おろします','ざんだかを かくにんします','てつづきを します'),'しつもんします','q018.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、まちで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('こうさてんを まがります','バスに のります','こうえんへ いきます','みちを たずねます'),'みちを たずねます','q019.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、こうじょうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします'),'あんぜんを かくにんします','q020.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、くうこうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ひこうきに のります','じかんを かくにんします','チェックインします','にもつを あずけます'),'じかんを かくにんします','q021.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、かいぎで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きろくを まとめます','よていを かくにんします','たんとうを きめます','いけんを はなします'),'きろくを まとめます','q022.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、てんきで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かさを もっていきます','うちで やすみます','そとへ でます','よていを かえます'),'よていを かえます','q023.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'この ばめんで、いちばん たいせつな ことは なんですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('でんしゃに のります','じかんを かくにんします','ホームへ いきます','きっぷを かいます'),'きっぷを かいます','q024.jpg',NULL,'えきで きっぷを かって、でんしゃの じかんを かくにんしてから、ホームへ いきます。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'この ばめんで、いちばん たいせつな ことは なんですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいものを おわります','うちへ かえります','やさいを えらびます','レジで はらいます'),'やさいを えらびます','q025.jpg',NULL,'スーパーで やさいと くだものを えらんでから、レジで おかねを はらいます。',true from parts p where part_number=1;

select 1 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=1;
