-- ITCO JAPAN | PART 01 | SOAL 21-30
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします'),'しごとを はじめます','q006.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ひこうきに のります','じかんを かくにんします','チェックインします','にもつを あずけます'),'にもつを あずけます','q007.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きろくを まとめます','よていを かくにんします','たんとうを きめます','いけんを はなします'),'たんとうを きめます','q008.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かさを もっていきます','うちで やすみます','そとへ でます','よていを かえます'),'うちで やすみます','q009.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、ひとは なにを しようと していますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('でんしゃに のります','じかんを かくにんします','ホームへ いきます','きっぷを かいます'),'じかんを かくにんします','q010.jpg',NULL,'えきで きっぷを かって、でんしゃの じかんを かくにんしてから、ホームへ いきます。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいものを おわります','うちへ かえります','やさいを えらびます','レジで はらいます'),'かいものを おわります',NULL,NULL,'スーパーで やさいと くだものを えらんでから、レジで おかねを はらいます。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかいけいを します','メニューを みます','ちゅうもんします','しょくじを します'),'しょくじを します',NULL,NULL,'レストランに はいって、メニューを みてから、りょうりを ちゅうもんします。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます'),'しりょうを かくにんします',NULL,NULL,'がっこうでは きょうしつで せんせいの せつめいを きいて、しりょうを かくにんします。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しりょうを まとめます','よていを かくにんします','メールを おくります','かいぎを します'),'よていを かくにんします',NULL,NULL,'かいしゃで みんなと かいぎを して、きまったことを しりょうに まとめます。',true from parts p where part_number=1;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('くすりを もらいます','よやくを かくにんします','うけつけを します','せんせいに そうだんします'),'くすりを もらいます',NULL,NULL,'びょういんに ついたら うけつけで なまえを つたえて、そのあと せんせいに そうだんします。',true from parts p where part_number=1;

select 1 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=1;
