-- ITCO JAPAN | PART 02 | SOAL 21-30
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます'),'しごとを はじめます','q031.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','チェックインします','にもつを あずけます','ひこうきに のります'),'にもつを あずけます','q032.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かくにんします','たんとうを きめます','いけんを はなします','きろくを まとめます'),'たんとうを きめます','q033.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うちで やすみます','そとへ でます','よていを かえます','かさを もっていきます'),'うちで やすみます','q034.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、ひとは なにを しようと していますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','ホームへ いきます','きっぷを かいます','でんしゃに のります'),'じかんを かくにんします','q035.jpg',NULL,'えきで きっぷを かって、でんしゃの じかんを かくにんしてから、ホームへ いきます。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うちへ かえります','やさいを えらびます','レジで はらいます','かいものを おわります'),'かいものを おわります',NULL,NULL,'スーパーで やさいと くだものを えらんでから、レジで おかねを はらいます。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('メニューを みます','ちゅうもんします','しょくじを します','おかいけいを します'),'しょくじを します',NULL,NULL,'レストランに はいって、メニューを みてから、りょうりを ちゅうもんします。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます','せんせいの せつめいを ききます'),'しりょうを かくにんします',NULL,NULL,'がっこうでは きょうしつで せんせいの せつめいを きいて、しりょうを かくにんします。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かくにんします','メールを おくります','かいぎを します','しりょうを まとめます'),'よていを かくにんします',NULL,NULL,'かいしゃで みんなと かいぎを して、きまったことを しりょうに まとめます。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よやくを かくにんします','うけつけを します','せんせいに そうだんします','くすりを もらいます'),'くすりを もらいます',NULL,NULL,'びょういんに ついたら うけつけで なまえを つたえて、そのあと せんせいに そうだんします。',true from parts p where part_number=2;

select 2 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=2;
