-- ITCO JAPAN | PART 02 | SOAL 31-40
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかねを おろします','ざんだかを かくにんします','てつづきを します','しつもんします'),'てつづきを します',NULL,NULL,'ぎんこうで ざんだかを かくにんしてから、おかねを おろします。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('バスに のります','こうえんへ いきます','みちを たずねます','こうさてんを まがります'),'こうえんへ いきます',NULL,NULL,'まちでは こうさてんを まがって、バスに のって、こうえんの まえまで いきます。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます'),'ヘルメットを かぶります',NULL,NULL,'こうじょうでは ヘルメットを かぶって、きかいと あんぜんを かくにんしてから しごとを はじめます。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','チェックインします','にもつを あずけます','ひこうきに のります'),'ひこうきに のります',NULL,NULL,'くうこうについたら じかんを かくにんして、にもつを あずけてから チェックインします。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かくにんします','たんとうを きめます','いけんを はなします','きろくを まとめます'),'いけんを はなします',NULL,NULL,'かいぎでは よていを かくにんして、たんとうを きめてから、きろくを まとめます。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、ひとは なにを しようと していますか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うちで やすみます','そとへ でます','よていを かえます','かさを もっていきます'),'そとへ でます','q036.jpg',NULL,'あめが ふりそうなので、かさを もっていきます。てんきが わるければ、そとの よていを かえる つもりです。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、えきで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','ホームへ いきます','きっぷを かいます','でんしゃに のります'),'ホームへ いきます','q037.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、スーパーで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うちへ かえります','やさいを えらびます','レジで はらいます','かいものを おわります'),'うちへ かえります','q038.jpg',NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、レストランで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('メニューを みます','ちゅうもんします','しょくじを します','おかいけいを します'),'おかいけいを します','q039.jpg',NULL,'よやくした ひとは なまえを つたえて、せきに ついて、メニューを みてから ちゅうもんします。',true from parts p where part_number=2;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、がっこうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます','せんせいの せつめいを ききます'),'しけんを うけます','q040.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。',true from parts p where part_number=2;

select 2 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=2;
