-- ITCO JAPAN | PART 03 | SOAL 21-30
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります'),'しごとを はじめます','q056.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 そのあと、ヘルメットを かぶります ことも あります。',true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('チェックインします','にもつを あずけます','ひこうきに のります','じかんを かくにんします'),'にもつを あずけます','q057.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 そのあと、ひこうきに のります ことも あります。',true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('たんとうを きめます','いけんを はなします','きろくを まとめます','よていを かくにんします'),'たんとうを きめます','q058.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 そのあと、いけんを はなします ことも あります。',true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('そとへ でます','よていを かえます','かさを もっていきます','うちで やすみます'),'うちで やすみます','q059.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 そのあと、そとへ でます ことも あります。',true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ホームへ いきます','きっぷを かいます','でんしゃに のります','じかんを かくにんします'),'じかんを かくにんします','q060.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 そのあと、ホームへ いきます ことも あります。',true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、はなしの なかでは どの こうどうを さきに しますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('やさいを えらびます','レジで はらいます','かいものを おわります','うちへ かえります'),'かいものを おわります',NULL,NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 そのあと、うちへ かえります ことも あります。',true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、はなしの なかでは どの こうどうを さきに しますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ちゅうもんします','しょくじを します','おかいけいを します','メニューを みます'),'しょくじを します',NULL,NULL,'よやくした ひとは なまえを つたえて、せきに ついて、メニューを みてから ちゅうもんします。 そのあと、おかいけいを します ことも あります。',true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、はなしの なかでは どの こうどうを さきに しますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しりょうを かくにんします','しけんを うけます','せんせいの せつめいを ききます','きょうしつで べんきょうします'),'しりょうを かくにんします',NULL,NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 そのあと、しけんを うけます ことも あります。',true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃで、はなしの なかでは どの こうどうを さきに しますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('メールを おくります','かいぎを します','しりょうを まとめます','よていを かくにんします'),'よていを かくにんします',NULL,NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 そのあと、メールを おくります ことも あります。',true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんで、はなしの なかでは どの こうどうを さきに しますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うけつけを します','せんせいに そうだんします','くすりを もらいます','よやくを かくにんします'),'くすりを もらいます',NULL,NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 そのあと、よやくを かくにんします ことも あります。',true from parts p where part_number=3;

select 3 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=3;
