-- ITCO JAPAN | PART 03 | SOAL 01-10
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ホームへ いきます','きっぷを かいます','でんしゃに のります','じかんを かくにんします'),'きっぷを かいます',NULL,NULL,NULL,true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('やさいを えらびます','レジで はらいます','かいものを おわります','うちへ かえります'),'やさいを えらびます',NULL,NULL,NULL,true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ちゅうもんします','しょくじを します','おかいけいを します','メニューを みます'),'メニューを みます',NULL,NULL,NULL,true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しりょうを かくにんします','しけんを うけます','せんせいの せつめいを ききます','きょうしつで べんきょうします'),'せんせいの せつめいを ききます',NULL,NULL,NULL,true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('メールを おくります','かいぎを します','しりょうを まとめます','よていを かくにんします'),'かいぎを します',NULL,NULL,NULL,true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うけつけを します','せんせいに そうだんします','くすりを もらいます','よやくを かくにんします'),'うけつけを します',NULL,NULL,NULL,true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ざんだかを かくにんします','てつづきを します','しつもんします','おかねを おろします'),'おかねを おろします',NULL,NULL,NULL,true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('こうえんへ いきます','みちを たずねます','こうさてんを まがります','バスに のります'),'こうさてんを まがります',NULL,NULL,NULL,true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります'),'きかいを かくにんします',NULL,NULL,NULL,true from parts p where part_number=3;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('チェックインします','にもつを あずけます','ひこうきに のります','じかんを かくにんします'),'チェックインします',NULL,NULL,NULL,true from parts p where part_number=3;

select 3 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=3;
