-- ITCO JAPAN | PART 04 | SOAL 31-40
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('てつづきを します','しつもんします','おかねを おろします','ざんだかを かくにんします'),'てつづきを します',NULL,NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 ただ、よていによっては おかねを おろします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('みちを たずねます','こうさてんを まがります','バスに のります','こうえんへ いきます'),'こうえんへ いきます',NULL,NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 ただ、よていによっては こうさてんを まがります ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします'),'ヘルメットを かぶります',NULL,NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 ただ、よていによっては きかいを かくにんします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('にもつを あずけます','ひこうきに のります','じかんを かくにんします','チェックインします'),'ひこうきに のります',NULL,NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 ただ、よていによっては チェックインします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('いけんを はなします','きろくを まとめます','よていを かくにんします','たんとうを きめます'),'いけんを はなします',NULL,NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 ただ、よていによっては よていを かくにんします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かえます','かさを もっていきます','うちで やすみます','そとへ でます'),'そとへ でます','q086.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 ただ、よていによっては かさを もっていきます ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きっぷを かいます','でんしゃに のります','じかんを かくにんします','ホームへ いきます'),'ホームへ いきます','q087.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 ただ、よていによっては でんしゃに のります ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('レジで はらいます','かいものを おわります','うちへ かえります','やさいを えらびます'),'うちへ かえります','q088.jpg',NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 ただ、よていによっては レジで はらいます ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しょくじを します','おかいけいを します','メニューを みます','ちゅうもんします'),'おかいけいを します','q089.jpg',NULL,'よやくした ひとは なまえを つたえて、せきに ついて、メニューを みてから ちゅうもんします。 ただ、よていによっては ちゅうもんします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しけんを うけます','せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします'),'しけんを うけます','q090.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 ただ、よていによっては きょうしつで べんきょうします ばあいも あります。',true from parts p where part_number=4;

select 4 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=4;
