-- ITCO JAPAN | PART 04 | SOAL 41-50
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいぎを します','しりょうを まとめます','よていを かくにんします','メールを おくります'),'メールを おくります','q091.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 ただ、よていによっては しりょうを まとめます ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいに そうだんします','くすりを もらいます','よやくを かくにんします','うけつけを します'),'よやくを かくにんします','q092.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 ただ、よていによっては せんせいに そうだんします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('てつづきを します','しつもんします','おかねを おろします','ざんだかを かくにんします'),'しつもんします','q093.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 ただ、よていによっては ざんだかを かくにんします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('みちを たずねます','こうさてんを まがります','バスに のります','こうえんへ いきます'),'みちを たずねます','q094.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 ただ、よていによっては バスに のります ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします'),'あんぜんを かくにんします','q095.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 ただ、よていによっては しごとを はじめます ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('にもつを あずけます','ひこうきに のります','じかんを かくにんします','チェックインします'),'じかんを かくにんします','q096.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 ただ、よていによっては にもつを あずけます ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('いけんを はなします','きろくを まとめます','よていを かくにんします','たんとうを きめます'),'きろくを まとめます','q097.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 ただ、よていによっては たんとうを きめます ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かえます','かさを もっていきます','うちで やすみます','そとへ でます'),'よていを かえます','q098.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 ただ、よていによっては うちで やすみます ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きっぷを かいます','でんしゃに のります','じかんを かくにんします','ホームへ いきます'),'きっぷを かいます','q099.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 ただ、よていによっては じかんを かくにんします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('レジで はらいます','かいものを おわります','うちへ かえります','やさいを えらびます'),'やさいを えらびます','q100.jpg',NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 ただ、よていによっては かいものを おわります ばあいも あります。',true from parts p where part_number=4;

select 4 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=4;
