-- ITCO JAPAN | PART 04 | SOAL 11-20
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('いけんを はなします','きろくを まとめます','よていを かくにんします','たんとうを きめます'),'よていを かくにんします',NULL,NULL,NULL,true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かえます','かさを もっていきます','うちで やすみます','そとへ でます'),'かさを もっていきます',NULL,NULL,NULL,true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きっぷを かいます','でんしゃに のります','じかんを かくにんします','ホームへ いきます'),'でんしゃに のります',NULL,NULL,NULL,true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('レジで はらいます','かいものを おわります','うちへ かえります','やさいを えらびます'),'レジで はらいます',NULL,NULL,NULL,true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しょくじを します','おかいけいを します','メニューを みます','ちゅうもんします'),'ちゅうもんします',NULL,NULL,NULL,true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しけんを うけます','せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします'),'きょうしつで べんきょうします','q076.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 ただ、よていによっては しけんを うけます ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいぎを します','しりょうを まとめます','よていを かくにんします','メールを おくります'),'しりょうを まとめます','q077.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 ただ、よていによっては メールを おくります ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいに そうだんします','くすりを もらいます','よやくを かくにんします','うけつけを します'),'せんせいに そうだんします','q078.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 ただ、よていによっては よやくを かくにんします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('てつづきを します','しつもんします','おかねを おろします','ざんだかを かくにんします'),'ざんだかを かくにんします','q079.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 ただ、よていによっては しつもんします ばあいも あります。',true from parts p where part_number=4;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('みちを たずねます','こうさてんを まがります','バスに のります','こうえんへ いきます'),'バスに のります','q080.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 ただ、よていによっては みちを たずねます ばあいも あります。',true from parts p where part_number=4;

select 4 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=4;
