-- ITCO JAPAN | PART 05 | SOAL 11-20
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きろくを まとめます','よていを かくにんします','たんとうを きめます','いけんを はなします'),'たんとうを きめます',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かさを もっていきます','うちで やすみます','そとへ でます','よていを かえます'),'うちで やすみます',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('でんしゃに のります','じかんを かくにんします','ホームへ いきます','きっぷを かいます'),'でんしゃに のります',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいものを おわります','うちへ かえります','やさいを えらびます','レジで はらいます'),'レジで はらいます',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかいけいを します','メニューを みます','ちゅうもんします','しょくじを します'),'ちゅうもんします',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます'),'きょうしつで べんきょうします','q101.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 すぐに それを するのではなく、しりょうを かくにんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しりょうを まとめます','よていを かくにんします','メールを おくります','かいぎを します'),'しりょうを まとめます','q102.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 すぐに それを するのではなく、よていを かくにんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('くすりを もらいます','よやくを かくにんします','うけつけを します','せんせいに そうだんします'),'せんせいに そうだんします','q103.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 すぐに それを するのではなく、くすりを もらいます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しつもんします','おかねを おろします','ざんだかを かくにんします','てつづきを します'),'ざんだかを かくにんします','q104.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 すぐに それを するのではなく、てつづきを します ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('こうさてんを まがります','バスに のります','こうえんへ いきます','みちを たずねます'),'バスに のります','q105.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 すぐに それを するのではなく、こうえんへ いきます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;

select 5 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=5;
