-- ITCO JAPAN | PART 05 | SOAL 01-10
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('でんしゃに のります','じかんを かくにんします','ホームへ いきます','きっぷを かいます'),'でんしゃに のります',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいものを おわります','うちへ かえります','やさいを えらびます','レジで はらいます'),'レジで はらいます',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかいけいを します','メニューを みます','ちゅうもんします','しょくじを します'),'ちゅうもんします',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます'),'きょうしつで べんきょうします',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しりょうを まとめます','よていを かくにんします','メールを おくります','かいぎを します'),'しりょうを まとめます',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('くすりを もらいます','よやくを かくにんします','うけつけを します','せんせいに そうだんします'),'せんせいに そうだんします',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しつもんします','おかねを おろします','ざんだかを かくにんします','てつづきを します'),'ざんだかを かくにんします',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('こうさてんを まがります','バスに のります','こうえんへ いきます','みちを たずねます'),'バスに のります',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします'),'しごとを はじめます',NULL,NULL,NULL,true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ひこうきに のります','じかんを かくにんします','チェックインします','にもつを あずけます'),'にもつを あずけます',NULL,NULL,NULL,true from parts p where part_number=5;

select 5 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=5;
