-- ITCO JAPAN | PART 05 | SOAL 21-30
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします'),'しごとを はじめます','q106.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 すぐに それを するのではなく、ヘルメットを かぶります ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ひこうきに のります','じかんを かくにんします','チェックインします','にもつを あずけます'),'にもつを あずけます','q107.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 すぐに それを するのではなく、ひこうきに のります ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きろくを まとめます','よていを かくにんします','たんとうを きめます','いけんを はなします'),'たんとうを きめます','q108.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 すぐに それを するのではなく、いけんを はなします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かさを もっていきます','うちで やすみます','そとへ でます','よていを かえます'),'うちで やすみます','q109.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 すぐに それを するのではなく、そとへ でます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('でんしゃに のります','じかんを かくにんします','ホームへ いきます','きっぷを かいます'),'ホームへ いきます','q110.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 すぐに それを するのではなく、ホームへ いきます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいものを おわります','うちへ かえります','やさいを えらびます','レジで はらいます'),'うちへ かえります',NULL,NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 すぐに それを するのではなく、うちへ かえります ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかいけいを します','メニューを みます','ちゅうもんします','しょくじを します'),'おかいけいを します',NULL,NULL,'よやくした ひとは なまえを つたえて、せきに ついて、メニューを みてから ちゅうもんします。 すぐに それを するのではなく、おかいけいを します ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます'),'しけんを うけます',NULL,NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 すぐに それを するのではなく、しけんを うけます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しりょうを まとめます','よていを かくにんします','メールを おくります','かいぎを します'),'メールを おくります',NULL,NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 すぐに それを するのではなく、メールを おくります ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('くすりを もらいます','よやくを かくにんします','うけつけを します','せんせいに そうだんします'),'よやくを かくにんします',NULL,NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 すぐに それを するのではなく、よやくを かくにんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;

select 5 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=5;
