-- ITCO JAPAN | PART 05 | SOAL 31-40
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しつもんします','おかねを おろします','ざんだかを かくにんします','てつづきを します'),'しつもんします',NULL,NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 すぐに それを するのではなく、しつもんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('こうさてんを まがります','バスに のります','こうえんへ いきます','みちを たずねます'),'みちを たずねます',NULL,NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 すぐに それを するのではなく、みちを たずねます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします'),'あんぜんを かくにんします',NULL,NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 すぐに それを するのではなく、あんぜんを かくにんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ひこうきに のります','じかんを かくにんします','チェックインします','にもつを あずけます'),'じかんを かくにんします',NULL,NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 すぐに それを するのではなく、じかんを かくにんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きろくを まとめます','よていを かくにんします','たんとうを きめます','いけんを はなします'),'きろくを まとめます',NULL,NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 すぐに それを するのではなく、きろくを まとめます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かさを もっていきます','うちで やすみます','そとへ でます','よていを かえます'),'よていを かえます','q111.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 すぐに それを するのではなく、よていを かえます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('でんしゃに のります','じかんを かくにんします','ホームへ いきます','きっぷを かいます'),'ホームへ いきます','q112.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 すぐに それを するのではなく、きっぷを かいます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいものを おわります','うちへ かえります','やさいを えらびます','レジで はらいます'),'うちへ かえります','q113.jpg',NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 すぐに それを するのではなく、やさいを えらびます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかいけいを します','メニューを みます','ちゅうもんします','しょくじを します'),'おかいけいを します','q114.jpg',NULL,'よやくした ひとは なまえを つたえて、せきに ついて、メニューを みてから ちゅうもんします。 すぐに それを するのではなく、メニューを みます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます'),'しけんを うけます','q115.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 すぐに それを するのではなく、せんせいの せつめいを ききます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=5;

select 5 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=5;
