-- ITCO JAPAN | PART 06 | SOAL 01-10
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','ホームへ いきます','きっぷを かいます','でんしゃに のります'),'でんしゃに のります',NULL,NULL,NULL,true from parts p where part_number=6;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うちへ かえります','やさいを えらびます','レジで はらいます','かいものを おわります'),'レジで はらいます',NULL,NULL,NULL,true from parts p where part_number=6;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('メニューを みます','ちゅうもんします','しょくじを します','おかいけいを します'),'ちゅうもんします',NULL,NULL,NULL,true from parts p where part_number=6;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます','せんせいの せつめいを ききます'),'きょうしつで べんきょうします',NULL,NULL,NULL,true from parts p where part_number=6;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かくにんします','メールを おくります','かいぎを します','しりょうを まとめます'),'しりょうを まとめます',NULL,NULL,NULL,true from parts p where part_number=6;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よやくを かくにんします','うけつけを します','せんせいに そうだんします','くすりを もらいます'),'せんせいに そうだんします',NULL,NULL,NULL,true from parts p where part_number=6;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかねを おろします','ざんだかを かくにんします','てつづきを します','しつもんします'),'ざんだかを かくにんします',NULL,NULL,NULL,true from parts p where part_number=6;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('バスに のります','こうえんへ いきます','みちを たずねます','こうさてんを まがります'),'バスに のります',NULL,NULL,NULL,true from parts p where part_number=6;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます'),'しごとを はじめます',NULL,NULL,NULL,true from parts p where part_number=6;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','チェックインします','にもつを あずけます','ひこうきに のります'),'にもつを あずけます',NULL,NULL,NULL,true from parts p where part_number=6;

select 6 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=6;
