-- ITCO JAPAN | PART 07 | SOAL 41-50
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、かいしゃで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('メールを おくります','かいぎを します','しりょうを まとめます','よていを かくにんします'),'メールを おくります','q166.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。',true from parts p where part_number=7;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、びょういんで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うけつけを します','せんせいに そうだんします','くすりを もらいます','よやくを かくにんします'),'よやくを かくにんします','q167.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。',true from parts p where part_number=7;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、ぎんこうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ざんだかを かくにんします','てつづきを します','しつもんします','おかねを おろします'),'しつもんします','q168.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。',true from parts p where part_number=7;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、まちで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('こうえんへ いきます','みちを たずねます','こうさてんを まがります','バスに のります'),'みちを たずねます','q169.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。',true from parts p where part_number=7;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、こうじょうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります'),'あんぜんを かくにんします','q170.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。',true from parts p where part_number=7;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、くうこうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('チェックインします','にもつを あずけます','ひこうきに のります','じかんを かくにんします'),'じかんを かくにんします','q171.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。',true from parts p where part_number=7;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、かいぎで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('たんとうを きめます','いけんを はなします','きろくを まとめます','よていを かくにんします'),'きろくを まとめます','q172.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。',true from parts p where part_number=7;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、てんきで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('そとへ でます','よていを かえます','かさを もっていきます','うちで やすみます'),'よていを かえます','q173.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。',true from parts p where part_number=7;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'この ばめんで、いちばん たいせつな ことは なんですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ホームへ いきます','きっぷを かいます','でんしゃに のります','じかんを かくにんします'),'きっぷを かいます','q174.jpg',NULL,'えきで きっぷを かって、でんしゃの じかんを かくにんしてから、ホームへ いきます。',true from parts p where part_number=7;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'この ばめんで、いちばん たいせつな ことは なんですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('やさいを えらびます','レジで はらいます','かいものを おわります','うちへ かえります'),'やさいを えらびます','q175.jpg',NULL,'スーパーで やさいと くだものを えらんでから、レジで おかねを はらいます。',true from parts p where part_number=7;

select 7 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=7;
