-- ITCO JAPAN | PART 08 | SOAL 41-50
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、かいしゃで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいぎを します','しりょうを まとめます','よていを かくにんします','メールを おくります'),'メールを おくります','q191.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、びょういんで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいに そうだんします','くすりを もらいます','よやくを かくにんします','うけつけを します'),'よやくを かくにんします','q192.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、ぎんこうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('てつづきを します','しつもんします','おかねを おろします','ざんだかを かくにんします'),'しつもんします','q193.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、まちで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('みちを たずねます','こうさてんを まがります','バスに のります','こうえんへ いきます'),'みちを たずねます','q194.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、こうじょうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします'),'あんぜんを かくにんします','q195.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、くうこうで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('にもつを あずけます','ひこうきに のります','じかんを かくにんします','チェックインします'),'じかんを かくにんします','q196.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、かいぎで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('いけんを はなします','きろくを まとめます','よていを かくにんします','たんとうを きめます'),'きろくを まとめます','q197.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'はなしを きいて、てんきで ただしい ものは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かえます','かさを もっていきます','うちで やすみます','そとへ でます'),'よていを かえます','q198.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'この ばめんで、いちばん たいせつな ことは なんですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きっぷを かいます','でんしゃに のります','じかんを かくにんします','ホームへ いきます'),'きっぷを かいます','q199.jpg',NULL,'えきで きっぷを かって、でんしゃの じかんを かくにんしてから、ホームへ いきます。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'この ばめんで、いちばん たいせつな ことは なんですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('レジで はらいます','かいものを おわります','うちへ かえります','やさいを えらびます'),'やさいを えらびます','q200.jpg',NULL,'スーパーで やさいと くだものを えらんでから、レジで おかねを はらいます。',true from parts p where part_number=8;

select 8 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=8;
