-- ITCO JAPAN | PART 08 | SOAL 21-30
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします'),'しごとを はじめます','q181.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('にもつを あずけます','ひこうきに のります','じかんを かくにんします','チェックインします'),'にもつを あずけます','q182.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('いけんを はなします','きろくを まとめます','よていを かくにんします','たんとうを きめます'),'たんとうを きめます','q183.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、そのあと なにを しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かえます','かさを もっていきます','うちで やすみます','そとへ でます'),'うちで やすみます','q184.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、ひとは なにを しようと していますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きっぷを かいます','でんしゃに のります','じかんを かくにんします','ホームへ いきます'),'じかんを かくにんします','q185.jpg',NULL,'えきで きっぷを かって、でんしゃの じかんを かくにんしてから、ホームへ いきます。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('レジで はらいます','かいものを おわります','うちへ かえります','やさいを えらびます'),'かいものを おわります',NULL,NULL,'スーパーで やさいと くだものを えらんでから、レジで おかねを はらいます。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しょくじを します','おかいけいを します','メニューを みます','ちゅうもんします'),'しょくじを します',NULL,NULL,'レストランに はいって、メニューを みてから、りょうりを ちゅうもんします。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しけんを うけます','せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします'),'しりょうを かくにんします',NULL,NULL,'がっこうでは きょうしつで せんせいの せつめいを きいて、しりょうを かくにんします。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいぎを します','しりょうを まとめます','よていを かくにんします','メールを おくります'),'よていを かくにんします',NULL,NULL,'かいしゃで みんなと かいぎを して、きまったことを しりょうに まとめます。',true from parts p where part_number=8;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんで、ひとは なにを しようと していますか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいに そうだんします','くすりを もらいます','よやくを かくにんします','うけつけを します'),'くすりを もらいます',NULL,NULL,'びょういんに ついたら うけつけで なまえを つたえて、そのあと せんせいに そうだんします。',true from parts p where part_number=8;

select 8 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=8;
