-- ITCO JAPAN | PART 09 | SOAL 11-20
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きろくを まとめます','よていを かくにんします','たんとうを きめます','いけんを はなします'),'よていを かくにんします',NULL,NULL,NULL,true from parts p where part_number=9;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かさを もっていきます','うちで やすみます','そとへ でます','よていを かえます'),'かさを もっていきます',NULL,NULL,NULL,true from parts p where part_number=9;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('でんしゃに のります','じかんを かくにんします','ホームへ いきます','きっぷを かいます'),'でんしゃに のります',NULL,NULL,NULL,true from parts p where part_number=9;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいものを おわります','うちへ かえります','やさいを えらびます','レジで はらいます'),'レジで はらいます',NULL,NULL,NULL,true from parts p where part_number=9;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、はなしの なかでは どの こうどうを さきに しますか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかいけいを します','メニューを みます','ちゅうもんします','しょくじを します'),'ちゅうもんします',NULL,NULL,NULL,true from parts p where part_number=9;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます'),'きょうしつで べんきょうします','q201.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 そのあと、しりょうを かくにんします ことも あります。',true from parts p where part_number=9;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しりょうを まとめます','よていを かくにんします','メールを おくります','かいぎを します'),'しりょうを まとめます','q202.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 そのあと、よていを かくにんします ことも あります。',true from parts p where part_number=9;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('くすりを もらいます','よやくを かくにんします','うけつけを します','せんせいに そうだんします'),'せんせいに そうだんします','q203.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 そのあと、くすりを もらいます ことも あります。',true from parts p where part_number=9;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しつもんします','おかねを おろします','ざんだかを かくにんします','てつづきを します'),'ざんだかを かくにんします','q204.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 そのあと、てつづきを します ことも あります。',true from parts p where part_number=9;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちで、はなしの なかでは どの こうどうを さきに しますか。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('こうさてんを まがります','バスに のります','こうえんへ いきます','みちを たずねます'),'バスに のります','q205.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 そのあと、こうえんへ いきます ことも あります。',true from parts p where part_number=9;

select 9 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=9;
