-- ITCO JAPAN | PART 10 | SOAL 01-10
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','ホームへ いきます','きっぷを かいます','でんしゃに のります'),'きっぷを かいます',NULL,NULL,NULL,true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うちへ かえります','やさいを えらびます','レジで はらいます','かいものを おわります'),'やさいを えらびます',NULL,NULL,NULL,true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('メニューを みます','ちゅうもんします','しょくじを します','おかいけいを します'),'メニューを みます',NULL,NULL,NULL,true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます','せんせいの せつめいを ききます'),'せんせいの せつめいを ききます',NULL,NULL,NULL,true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かくにんします','メールを おくります','かいぎを します','しりょうを まとめます'),'かいぎを します',NULL,NULL,NULL,true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よやくを かくにんします','うけつけを します','せんせいに そうだんします','くすりを もらいます'),'うけつけを します',NULL,NULL,NULL,true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかねを おろします','ざんだかを かくにんします','てつづきを します','しつもんします'),'おかねを おろします',NULL,NULL,NULL,true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('バスに のります','こうえんへ いきます','みちを たずねます','こうさてんを まがります'),'こうさてんを まがります',NULL,NULL,NULL,true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます'),'きかいを かくにんします',NULL,NULL,NULL,true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','チェックインします','にもつを あずけます','ひこうきに のります'),'チェックインします',NULL,NULL,NULL,true from parts p where part_number=10;

select 10 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=10;
