-- ITCO JAPAN | PART 10 | SOAL 31-40
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('おかねを おろします','ざんだかを かくにんします','てつづきを します','しつもんします'),'てつづきを します',NULL,NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 ただ、よていによっては おかねを おろします ばあいも あります。',true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('バスに のります','こうえんへ いきます','みちを たずねます','こうさてんを まがります'),'こうえんへ いきます',NULL,NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 ただ、よていによっては こうさてんを まがります ばあいも あります。',true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ヘルメットを かぶります','あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます'),'ヘルメットを かぶります',NULL,NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 ただ、よていによっては きかいを かくにんします ばあいも あります。',true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','チェックインします','にもつを あずけます','ひこうきに のります'),'ひこうきに のります',NULL,NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 ただ、よていによっては チェックインします ばあいも あります。',true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かくにんします','たんとうを きめます','いけんを はなします','きろくを まとめます'),'いけんを はなします',NULL,NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 ただ、よていによっては よていを かくにんします ばあいも あります。',true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うちで やすみます','そとへ でます','よていを かえます','かさを もっていきます'),'そとへ でます','q236.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 ただ、よていによっては かさを もっていきます ばあいも あります。',true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('じかんを かくにんします','ホームへ いきます','きっぷを かいます','でんしゃに のります'),'ホームへ いきます','q237.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 ただ、よていによっては でんしゃに のります ばあいも あります。',true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うちへ かえります','やさいを えらびます','レジで はらいます','かいものを おわります'),'うちへ かえります','q238.jpg',NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 ただ、よていによっては レジで はらいます ばあいも あります。',true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('メニューを みます','ちゅうもんします','しょくじを します','おかいけいを します'),'おかいけいを します','q239.jpg',NULL,'よやくした ひとは なまえを つたえて、せきに ついて、メニューを みてから ちゅうもんします。 ただ、よていによっては ちゅうもんします ばあいも あります。',true from parts p where part_number=10;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうで、はなしから わかる ただしい こうどうの じゅんばんは どれですか。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きょうしつで べんきょうします','しりょうを かくにんします','しけんを うけます','せんせいの せつめいを ききます'),'しけんを うけます','q240.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 ただ、よていによっては きょうしつで べんきょうします ばあいも あります。',true from parts p where part_number=10;

select 10 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=10;
