-- ITCO JAPAN | PART 11 | SOAL 41-50
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('メールを おくります','かいぎを します','しりょうを まとめます','よていを かくにんします'),'メールを おくります','q266.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 すぐに それを するのではなく、かいぎを します ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('うけつけを します','せんせいに そうだんします','くすりを もらいます','よやくを かくにんします'),'よやくを かくにんします','q267.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 すぐに それを するのではなく、うけつけを します ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ざんだかを かくにんします','てつづきを します','しつもんします','おかねを おろします'),'しつもんします','q268.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 すぐに それを するのではなく、おかねを おろします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('こうえんへ いきます','みちを たずねます','こうさてんを まがります','バスに のります'),'みちを たずねます','q269.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 すぐに それを するのではなく、こうさてんを まがります ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります'),'あんぜんを かくにんします','q270.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 すぐに それを するのではなく、きかいを かくにんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('チェックインします','にもつを あずけます','ひこうきに のります','じかんを かくにんします'),'じかんを かくにんします','q271.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 すぐに それを するのではなく、チェックインします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('たんとうを きめます','いけんを はなします','きろくを まとめます','よていを かくにんします'),'きろくを まとめます','q272.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 すぐに それを するのではなく、よていを かくにんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('そとへ でます','よていを かえます','かさを もっていきます','うちで やすみます'),'よていを かえます','q273.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 すぐに それを するのではなく、かさを もっていきます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ホームへ いきます','きっぷを かいます','でんしゃに のります','じかんを かくにんします'),'でんしゃに のります','q274.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 すぐに それを するのではなく、でんしゃに のります ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('やさいを えらびます','レジで はらいます','かいものを おわります','うちへ かえります'),'レジで はらいます','q275.jpg',NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 すぐに それを するのではなく、レジで はらいます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;

select 11 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=11;
