-- ITCO JAPAN | PART 11 | SOAL 31-40
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ざんだかを かくにんします','てつづきを します','しつもんします','おかねを おろします'),'しつもんします',NULL,NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 すぐに それを するのではなく、しつもんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('こうえんへ いきます','みちを たずねます','こうさてんを まがります','バスに のります'),'みちを たずねます',NULL,NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 すぐに それを するのではなく、みちを たずねます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('あんぜんを かくにんします','きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります'),'あんぜんを かくにんします',NULL,NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 すぐに それを するのではなく、あんぜんを かくにんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('チェックインします','にもつを あずけます','ひこうきに のります','じかんを かくにんします'),'じかんを かくにんします',NULL,NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 すぐに それを するのではなく、じかんを かくにんします ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('たんとうを きめます','いけんを はなします','きろくを まとめます','よていを かくにんします'),'きろくを まとめます',NULL,NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 すぐに それを するのではなく、きろくを まとめます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('そとへ でます','よていを かえます','かさを もっていきます','うちで やすみます'),'よていを かえます','q261.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 すぐに それを するのではなく、よていを かえます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ホームへ いきます','きっぷを かいます','でんしゃに のります','じかんを かくにんします'),'ホームへ いきます','q262.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 すぐに それを するのではなく、きっぷを かいます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('やさいを えらびます','レジで はらいます','かいものを おわります','うちへ かえります'),'うちへ かえります','q263.jpg',NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 すぐに それを するのではなく、やさいを えらびます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('ちゅうもんします','しょくじを します','おかいけいを します','メニューを みます'),'おかいけいを します','q264.jpg',NULL,'よやくした ひとは なまえを つたえて、せきに ついて、メニューを みてから ちゅうもんします。 すぐに それを するのではなく、メニューを みます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうの ばめんについて、はなしの ないようから もっとも ただしい せつめいを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しりょうを かくにんします','しけんを うけます','せんせいの せつめいを ききます','きょうしつで べんきょうします'),'しけんを うけます','q265.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 すぐに それを するのではなく、せんせいの せつめいを ききます ことを さきに します。だから、さいしょの よていとは じゅんばんが ちがいます。',true from parts p where part_number=11;

select 11 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=11;
