-- ITCO JAPAN | PART 12 | SOAL 31-40
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('てつづきを します','しつもんします','おかねを おろします','ざんだかを かくにんします'),'しつもんします',NULL,NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 とはいえ、じょうきょうが かわれば おかねを おろします ひつようが あります。はなしの なかでは、しつもんします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('みちを たずねます','こうさてんを まがります','バスに のります','こうえんへ いきます'),'みちを たずねます',NULL,NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 とはいえ、じょうきょうが かわれば こうさてんを まがります ひつようが あります。はなしの なかでは、みちを たずねます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします'),'あんぜんを かくにんします',NULL,NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 とはいえ、じょうきょうが かわれば きかいを かくにんします ひつようが あります。はなしの なかでは、あんぜんを かくにんします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('にもつを あずけます','ひこうきに のります','じかんを かくにんします','チェックインします'),'じかんを かくにんします',NULL,NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 とはいえ、じょうきょうが かわれば チェックインします ひつようが あります。はなしの なかでは、じかんを かくにんします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('いけんを はなします','きろくを まとめます','よていを かくにんします','たんとうを きめます'),'きろくを まとめます',NULL,NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 とはいえ、じょうきょうが かわれば よていを かくにんします ひつようが あります。はなしの なかでは、きろくを まとめます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かえます','かさを もっていきます','うちで やすみます','そとへ でます'),'よていを かえます','q286.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 とはいえ、じょうきょうが かわれば かさを もっていきます ひつようが あります。はなしの なかでは、よていを かえます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きっぷを かいます','でんしゃに のります','じかんを かくにんします','ホームへ いきます'),'きっぷを かいます','q287.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 とはいえ、じょうきょうが かわれば でんしゃに のります ひつようが あります。はなしの なかでは、きっぷを かいます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('レジで はらいます','かいものを おわります','うちへ かえります','やさいを えらびます'),'やさいを えらびます','q288.jpg',NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 とはいえ、じょうきょうが かわれば レジで はらいます ひつようが あります。はなしの なかでは、やさいを えらびます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しょくじを します','おかいけいを します','メニューを みます','ちゅうもんします'),'メニューを みます','q289.jpg',NULL,'よやくした ひとは なまえを つたえて、せきに ついて、メニューを みてから ちゅうもんします。 とはいえ、じょうきょうが かわれば ちゅうもんします ひつようが あります。はなしの なかでは、メニューを みます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しけんを うけます','せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします'),'せんせいの せつめいを ききます','q290.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 とはいえ、じょうきょうが かわれば きょうしつで べんきょうします ひつようが あります。はなしの なかでは、せんせいの せつめいを ききます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;

select 12 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=12;
