-- ITCO JAPAN | PART 12 | SOAL 41-50
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいぎを します','しりょうを まとめます','よていを かくにんします','メールを おくります'),'かいぎを します','q291.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 とはいえ、じょうきょうが かわれば しりょうを まとめます ひつようが あります。はなしの なかでは、かいぎを します ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいに そうだんします','くすりを もらいます','よやくを かくにんします','うけつけを します'),'うけつけを します','q292.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 とはいえ、じょうきょうが かわれば せんせいに そうだんします ひつようが あります。はなしの なかでは、うけつけを します ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('てつづきを します','しつもんします','おかねを おろします','ざんだかを かくにんします'),'おかねを おろします','q293.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 とはいえ、じょうきょうが かわれば ざんだかを かくにんします ひつようが あります。はなしの なかでは、おかねを おろします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('みちを たずねます','こうさてんを まがります','バスに のります','こうえんへ いきます'),'こうさてんを まがります','q294.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 とはいえ、じょうきょうが かわれば バスに のります ひつようが あります。はなしの なかでは、こうさてんを まがります ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします'),'きかいを かくにんします','q295.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 とはいえ、じょうきょうが かわれば しごとを はじめます ひつようが あります。はなしの なかでは、きかいを かくにんします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('にもつを あずけます','ひこうきに のります','じかんを かくにんします','チェックインします'),'チェックインします','q296.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 とはいえ、じょうきょうが かわれば にもつを あずけます ひつようが あります。はなしの なかでは、チェックインします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('いけんを はなします','きろくを まとめます','よていを かくにんします','たんとうを きめます'),'よていを かくにんします','q297.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 とはいえ、じょうきょうが かわれば たんとうを きめます ひつようが あります。はなしの なかでは、よていを かくにんします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かえます','かさを もっていきます','うちで やすみます','そとへ でます'),'かさを もっていきます','q298.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 とはいえ、じょうきょうが かわれば うちで やすみます ひつようが あります。はなしの なかでは、かさを もっていきます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きっぷを かいます','でんしゃに のります','じかんを かくにんします','ホームへ いきます'),'でんしゃに のります','q299.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 とはいえ、じょうきょうが かわれば じかんを かくにんします ひつようが あります。はなしの なかでは、でんしゃに のります ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto dan 🔊 dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('レジで はらいます','かいものを おわります','うちへ かえります','やさいを えらびます'),'レジで はらいます','q300.jpg',NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 とはいえ、じょうきょうが かわれば かいものを おわります ひつようが あります。はなしの なかでは、レジで はらいます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;

select 12 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=12;
