-- ITCO JAPAN | PART 12 | SOAL 11-20
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('いけんを はなします','きろくを まとめます','よていを かくにんします','たんとうを きめます'),'たんとうを きめます',NULL,NULL,NULL,true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かえます','かさを もっていきます','うちで やすみます','そとへ でます'),'うちで やすみます',NULL,NULL,NULL,true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きっぷを かいます','でんしゃに のります','じかんを かくにんします','ホームへ いきます'),'じかんを かくにんします',NULL,NULL,NULL,true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('レジで はらいます','かいものを おわります','うちへ かえります','やさいを えらびます'),'かいものを おわります',NULL,NULL,NULL,true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','Pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しょくじを します','おかいけいを します','メニューを みます','ちゅうもんします'),'しょくじを します',NULL,NULL,NULL,true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しけんを うけます','せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします'),'しりょうを かくにんします','q276.jpg',NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 とはいえ、じょうきょうが かわれば しけんを うけます ひつようが あります。はなしの なかでは、しりょうを かくにんします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいぎを します','しりょうを まとめます','よていを かくにんします','メールを おくります'),'よていを かくにんします','q277.jpg',NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 とはいえ、じょうきょうが かわれば メールを おくります ひつようが あります。はなしの なかでは、よていを かくにんします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいに そうだんします','くすりを もらいます','よやくを かくにんします','うけつけを します'),'くすりを もらいます','q278.jpg',NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 とはいえ、じょうきょうが かわれば よやくを かくにんします ひつようが あります。はなしの なかでは、くすりを もらいます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'ぎんこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('てつづきを します','しつもんします','おかねを おろします','ざんだかを かくにんします'),'てつづきを します','q279.jpg',NULL,'ひつような てつづきを するまえに、ざんだかと ひつような しょるいを かくにんします。 とはいえ、じょうきょうが かわれば しつもんします ひつようが あります。はなしの なかでは、てつづきを します ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'まちの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('みちを たずねます','こうさてんを まがります','バスに のります','こうえんへ いきます'),'こうえんへ いきます','q280.jpg',NULL,'みちが わからなかったので、ちかくの ひとに たずねてから、こうえんへ むかいました。 とはいえ、じょうきょうが かわれば みちを たずねます ひつようが あります。はなしの なかでは、こうえんへ いきます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;

select 12 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=12;
