-- ITCO JAPAN | PART 12 | SOAL 21-30
-- Jalankan setelah 01_SETUP.sql. Jalankan file PART ini berurutan.

insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'こうじょうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きかいを かくにんします','しごとを はじめます','ヘルメットを かぶります','あんぜんを かくにんします'),'ヘルメットを かぶります','q281.jpg',NULL,'しごとの まえに きかいの じょうたいを かくにんし、あんぜんを たしかめてから さぎょうします。 とはいえ、じょうきょうが かわれば あんぜんを かくにんします ひつようが あります。はなしの なかでは、ヘルメットを かぶります ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'くうこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('にもつを あずけます','ひこうきに のります','じかんを かくにんします','チェックインします'),'ひこうきに のります','q282.jpg',NULL,'ひこうきに のるまえに チェックインを して、にもつを あずけ、それから とうじょうぐちへ むかいます。 とはいえ、じょうきょうが かわれば じかんを かくにんします ひつようが あります。はなしの なかでは、ひこうきに のります ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいぎの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('いけんを はなします','きろくを まとめます','よていを かくにんします','たんとうを きめます'),'いけんを はなします','q283.jpg',NULL,'みんなが いけんを はなしたあと、きまったことと たんとうを きろくに のこします。 とはいえ、じょうきょうが かわれば きろくを まとめます ひつようが あります。はなしの なかでは、いけんを はなします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'てんきの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('よていを かえます','かさを もっていきます','うちで やすみます','そとへ でます'),'そとへ でます','q284.jpg',NULL,'あめが つよくなったら そとへ でる よていを かえて、うちで やすむ ことに します。 とはいえ、じょうきょうが かわれば よていを かえます ひつようが あります。はなしの なかでは、そとへ でます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'えきの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','📷 Perhatikan foto/situasi, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('きっぷを かいます','でんしゃに のります','じかんを かくにんします','ホームへ いきます'),'ホームへ いきます','q285.jpg',NULL,'えきに ついたあと、きっぷを かって、じかんを みて、それから ホームへ むかいます。 とはいえ、じょうきょうが かわれば きっぷを かいます ひつようが あります。はなしの なかでは、ホームへ いきます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'スーパーの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('レジで はらいます','かいものを おわります','うちへ かえります','やさいを えらびます'),'うちへ かえります',NULL,NULL,'スーパーでは さきに かうものを えらび、そのあと レジへ いって、おかねを はらいます。 とはいえ、じょうきょうが かわれば やさいを えらびます ひつようが あります。はなしの なかでは、うちへ かえります ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'レストランの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しょくじを します','おかいけいを します','メニューを みます','ちゅうもんします'),'おかいけいを します',NULL,NULL,'よやくした ひとは なまえを つたえて、せきに ついて、メニューを みてから ちゅうもんします。 とはいえ、じょうきょうが かわれば メニューを みます ひつようが あります。はなしの なかでは、おかいけいを します ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'がっこうの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('しけんを うけます','せんせいの せつめいを ききます','きょうしつで べんきょうします','しりょうを かくにんします'),'しけんを うけます',NULL,NULL,'しけんの まえに ひつような しりょうを そろえて、せんせいの せつめいを ききます。 とはいえ、じょうきょうが かわれば せんせいの せつめいを ききます ひつようが あります。はなしの なかでは、しけんを うけます ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'かいしゃの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('かいぎを します','しりょうを まとめます','よていを かくにんします','メールを おくります'),'メールを おくります',NULL,NULL,'かいぎの あとで きまったことを まとめて、たんとうの ひとに メールで おくります。 とはいえ、じょうきょうが かわれば かいぎを します ひつようが あります。はなしの なかでは、メールを おくります ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;
insert into questions (part_id,prompt,instruction,type,options,answer,photo_url,audio_url,audio_text,active) select p.id,'びょういんの ばめんについて、はなしから よみとれる いみとして もっとも ただしい ものを えらんでください。','🔊 Dengarkan audio Jepang, lalu pilih jawaban yang paling tepat.','multiple_choice',jsonb_build_array('せんせいに そうだんします','くすりを もらいます','よやくを かくにんします','うけつけを します'),'よやくを かくにんします',NULL,NULL,'よやくの じかんを かくにんしてから うけつけへ いき、せんせいに しょうじょうを はなします。 とはいえ、じょうきょうが かわれば うけつけを します ひつようが あります。はなしの なかでは、よやくを かくにんします ことを さきに おこなうと せつめいしています。',true from parts p where part_number=12;

select 12 as part_number, count(*) as total_soal from public.questions q join public.parts p on p.id=q.part_id where p.part_number=12;
