-- ================================================================
-- ITCO JAPAN - USER MONITORING + USER RESULTS + HIRAGANA TEST
-- Jalankan SEKALI setelah supabase-accounts.sql.
-- Fitur ini menambah monitoring akun tanpa menghapus data fitur lama.
-- ================================================================

-- 1) Profil user yang aman dibaca aplikasi melalui akun sendiri / Admin RPC.
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text not null default '',
  created_at timestamptz not null default now(),
  last_login_at timestamptz,
  last_logout_at timestamptz,
  last_seen_at timestamptz,
  login_count integer not null default 0,
  last_device text,
  disabled boolean not null default false,
  updated_at timestamptz not null default now()
);
alter table public.user_profiles enable row level security;

-- 2) Riwayat login/logout.
create table if not exists public.user_login_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  login_at timestamptz not null default now(),
  logout_at timestamptz,
  device text,
  user_agent text,
  page text
);
create index if not exists user_login_history_user_idx on public.user_login_history(user_id, login_at desc);
alter table public.user_login_history enable row level security;

-- 3) Aktivitas user.
create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  page text,
  device text
);
create index if not exists user_activity_user_idx on public.user_activity(user_id, created_at desc);
alter table public.user_activity enable row level security;

-- 4) Heartbeat/status online.
create table if not exists public.user_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_seen_at timestamptz not null default now(),
  page text,
  device text,
  updated_at timestamptz not null default now()
);
alter table public.user_presence enable row level security;

-- 5) Hasil tes khusus (dipisah dari results lama agar fitur latihan lama aman).
create table if not exists public.assessment_results (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  test_type text not null,
  score integer not null default 0,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  unanswered_count integer not null default 0,
  duration_seconds integer not null default 0,
  details jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists assessment_results_user_idx on public.assessment_results(user_id, created_at desc);
alter table public.assessment_results enable row level security;

-- 6) Kaitkan hasil latihan lama/baru dengan ID akun.
alter table public.results add column if not exists user_id uuid references auth.users(id) on delete set null;
create index if not exists results_user_idx on public.results(user_id, created_at desc);

-- 7) Isi profil untuk akun yang sudah ada.
insert into public.user_profiles(user_id,name,email,created_at,updated_at)
select u.id, coalesce(u.raw_user_meta_data->>'name',''), coalesce(u.email,''), u.created_at, now()
from auth.users u
on conflict (user_id) do update set
  name=excluded.name,
  email=excluded.email,
  updated_at=now();

-- Backfill hasil lama hanya jika nama cocok tepat ke SATU akun.
with unique_names as (
  select lower(trim(name)) as nm, (array_agg(user_id order by user_id))[1] as user_id
  from public.user_profiles
  where trim(name) <> ''
  group by lower(trim(name))
  having count(*) = 1
)
update public.results r
set user_id=u.user_id
from unique_names u
where r.user_id is null and lower(trim(coalesce(r.name,'')))=u.nm;

-- 8) Trigger profil saat akun baru dibuat.
create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_profiles(user_id,name,email,created_at,updated_at)
  values (new.id, coalesce(new.raw_user_meta_data->>'name',''), coalesce(new.email,''), new.created_at, now())
  on conflict (user_id) do update set
    name=excluded.name,
    email=excluded.email,
    updated_at=now();
  return new;
end;
$$;
drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();

-- 9) Fungsi user: login, logout, heartbeat, aktivitas.
create or replace function public.record_user_login(p_device text default null, p_page text default null)
returns void language plpgsql security definer set search_path=public
as $$
declare uid uuid := auth.uid();
declare lid uuid;
begin
  if uid is null then return; end if;
  insert into public.user_profiles(user_id,name,email,created_at)
  select id, coalesce(raw_user_meta_data->>'name',''), coalesce(email,''), created_at from auth.users where id=uid
  on conflict (user_id) do nothing;
  update public.user_profiles
  set last_login_at=now(), last_seen_at=now(), login_count=login_count+1,
      last_device=left(coalesce(p_device,''),200), updated_at=now()
  where user_id=uid;
  insert into public.user_login_history(user_id,login_at,device,user_agent,page)
  values(uid,now(),left(coalesce(p_device,''),200),left(coalesce((coalesce(current_setting('request.headers',true),'{}')::jsonb)->>'user-agent',''),500),left(coalesce(p_page,''),200))
  returning id into lid;
  insert into public.user_presence(user_id,last_seen_at,page,device,updated_at)
  values(uid,now(),left(coalesce(p_page,''),200),left(coalesce(p_device,''),200),now())
  on conflict(user_id) do update set last_seen_at=now(),page=excluded.page,device=excluded.device,updated_at=now();
end;
$$;

create or replace function public.record_user_logout()
returns void language plpgsql security definer set search_path=public
as $$
declare uid uuid := auth.uid();
begin
  if uid is null then return; end if;
  update public.user_profiles set last_logout_at=now(), last_seen_at=now(), updated_at=now() where user_id=uid;
  update public.user_login_history set logout_at=now()
  where id=(select id from public.user_login_history where user_id=uid and logout_at is null order by login_at desc limit 1);
  delete from public.user_presence where user_id=uid;
end;
$$;

create or replace function public.record_user_presence(p_page text default null, p_device text default null)
returns void language plpgsql security definer set search_path=public
as $$
declare uid uuid := auth.uid();
begin
  if uid is null then return; end if;
  update public.user_profiles set last_seen_at=now(), last_device=left(coalesce(p_device,''),200), updated_at=now() where user_id=uid;
  insert into public.user_presence(user_id,last_seen_at,page,device,updated_at)
  values(uid,now(),left(coalesce(p_page,''),200),left(coalesce(p_device,''),200),now())
  on conflict(user_id) do update set last_seen_at=now(),page=excluded.page,device=excluded.device,updated_at=now();
end;
$$;

create or replace function public.record_user_activity(p_action text, p_detail jsonb default '{}'::jsonb, p_page text default null, p_device text default null)
returns void language plpgsql security definer set search_path=public
as $$
declare uid uuid := auth.uid();
begin
  if uid is null then return; end if;
  insert into public.user_activity(user_id,action,detail,page,device)
  values(uid,left(coalesce(p_action,''),120),coalesce(p_detail,'{}'::jsonb),left(coalesce(p_page,''),200),left(coalesce(p_device,''),200));
  update public.user_profiles set last_seen_at=now(),last_device=left(coalesce(p_device,''),200),updated_at=now() where user_id=uid;
end;
$$;

-- 10) RPC Admin: daftar user, detail user, nonaktifkan, hapus.
create or replace function public.admin_list_users()
returns jsonb language plpgsql security definer set search_path=public
as $$
declare out jsonb;
begin
  if not public.is_admin() then raise exception 'Not authorized'; end if;
  select coalesce(jsonb_agg(row_to_json(x)::jsonb order by x.created_at desc),'[]'::jsonb) into out
  from (
    select p.user_id,p.name,p.email,p.created_at,p.last_login_at,p.last_logout_at,p.last_seen_at,p.login_count,p.last_device,p.disabled,
      (pr.user_id is not null and pr.last_seen_at >= now()-interval '45 seconds') as online,
      pr.page as current_page,
      coalesce((select count(*) from public.results r where r.user_id=p.user_id),0) as result_count,
      coalesce((select count(*) from public.assessment_results a where a.user_id=p.user_id),0) as assessment_count
    from public.user_profiles p left join public.user_presence pr on pr.user_id=p.user_id
  ) x;
  return out;
end;
$$;

create or replace function public.admin_get_user_detail(p_user_id uuid)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare out jsonb;
begin
  if not public.is_admin() then raise exception 'Not authorized'; end if;
  select jsonb_build_object(
    'profile',(select row_to_json(p)::jsonb from public.user_profiles p where p.user_id=p_user_id),
    'presence',(select row_to_json(pr)::jsonb from public.user_presence pr where pr.user_id=p_user_id),
    'logins',coalesce((select jsonb_agg(row_to_json(l)::jsonb order by l.login_at desc) from (select * from public.user_login_history where user_id=p_user_id order by login_at desc limit 200) l),'[]'::jsonb),
    'activities',coalesce((select jsonb_agg(row_to_json(a)::jsonb order by a.created_at desc) from (select * from public.user_activity where user_id=p_user_id order by created_at desc limit 300) a),'[]'::jsonb),
    'results',coalesce((select jsonb_agg(to_jsonb(r)||jsonb_build_object('part_name',p2.name,'part_number',p2.part_number) order by r.created_at desc) from (select * from public.results where user_id=p_user_id order by created_at desc limit 100) r left join public.parts p2 on p2.id=r.part_id),'[]'::jsonb),
    'assessments',coalesce((select jsonb_agg(row_to_json(ar)::jsonb order by ar.created_at desc) from (select * from public.assessment_results where user_id=p_user_id order by created_at desc limit 100) ar),'[]'::jsonb),
    'devices',coalesce((select jsonb_agg(distinct l.device) from public.user_login_history l where l.user_id=p_user_id and coalesce(l.device,'')<>''),'[]'::jsonb)
  ) into out;
  return coalesce(out,'{}'::jsonb);
end;
$$;

create or replace function public.admin_set_user_disabled(p_user_id uuid, p_disabled boolean)
returns boolean language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_admin() then raise exception 'Not authorized'; end if;
  if p_user_id = auth.uid() then raise exception 'Tidak bisa menonaktifkan akun Admin yang sedang dipakai'; end if;
  update public.user_profiles set disabled=p_disabled,updated_at=now() where user_id=p_user_id;
  update auth.users set banned_until=case when p_disabled then 'infinity'::timestamptz else null end where id=p_user_id;
  return true;
end;
$$;

create or replace function public.admin_delete_user(p_user_id uuid)
returns boolean language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_admin() then raise exception 'Not authorized'; end if;
  if p_user_id = auth.uid() then raise exception 'Tidak bisa menghapus akun Admin yang sedang dipakai'; end if;
  delete from public.results where user_id=p_user_id;
  delete from public.assessment_results where user_id=p_user_id;
  delete from public.user_names where name=(select name from public.user_profiles where user_id=p_user_id);
  delete from auth.users where id=p_user_id;
  return true;
end;
$$;

-- 11) RLS: user hanya melihat data miliknya; Admin melihat lewat RPC / tabel yang relevan.
drop policy if exists "akun_anon_tidak_insert" on public.results;
drop policy if exists "akun_admin_select" on public.results;
drop policy if exists "akun_admin_update" on public.results;
drop policy if exists "akun_admin_delete" on public.results;
drop policy if exists "results_user_select" on public.results;
drop policy if exists "results_user_insert" on public.results;
drop policy if exists "results_admin_select" on public.results;
drop policy if exists "results_admin_update" on public.results;
drop policy if exists "results_admin_delete" on public.results;
alter table public.results enable row level security;
create policy "results_user_select" on public.results for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy "results_user_insert" on public.results for insert to authenticated with check (user_id=auth.uid());
create policy "results_admin_update" on public.results for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "results_admin_delete" on public.results for delete to authenticated using (public.is_admin());

-- Profil/login/activity/presence tidak dibaca langsung user lain.
drop policy if exists "profile_self_select" on public.user_profiles;
drop policy if exists "profile_self_update" on public.user_profiles;
create policy "profile_self_select" on public.user_profiles for select to authenticated using (user_id=auth.uid() or public.is_admin());

drop policy if exists "login_self_select" on public.user_login_history;
create policy "login_self_select" on public.user_login_history for select to authenticated using (user_id=auth.uid() or public.is_admin());

drop policy if exists "activity_self_select" on public.user_activity;
create policy "activity_self_select" on public.user_activity for select to authenticated using (user_id=auth.uid() or public.is_admin());

drop policy if exists "presence_self_select" on public.user_presence;
create policy "presence_self_select" on public.user_presence for select to authenticated using (user_id=auth.uid() or public.is_admin());

-- assessment_results: user boleh menyimpan & melihat miliknya, Admin juga bisa.
drop policy if exists "assessment_self_select" on public.assessment_results;
drop policy if exists "assessment_self_insert" on public.assessment_results;
drop policy if exists "assessment_admin_delete" on public.assessment_results;
create policy "assessment_self_select" on public.assessment_results for select to authenticated using (user_id=auth.uid() or public.is_admin());
create policy "assessment_self_insert" on public.assessment_results for insert to authenticated with check (user_id=auth.uid());
create policy "assessment_admin_delete" on public.assessment_results for delete to authenticated using (public.is_admin());

-- Hanya fungsi yang diperlukan yang dapat dipanggil.
grant execute on function public.record_user_login(text,text) to authenticated;
grant execute on function public.record_user_logout() to authenticated;
grant execute on function public.record_user_presence(text,text) to authenticated;
grant execute on function public.record_user_activity(text,jsonb,text,text) to authenticated;
grant execute on function public.admin_list_users() to authenticated;
grant execute on function public.admin_get_user_detail(uuid) to authenticated;
grant execute on function public.admin_set_user_disabled(uuid,boolean) to authenticated;
grant execute on function public.admin_delete_user(uuid) to authenticated;

notify pgrst, 'reload schema';

